---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: greeting-sample
    app.kubernetes.io/version: {{ .Values.app.version }}
    app.openshift.io/runtime: quarkus
  name: greeting-sample-{{ regexReplaceAll "\\W+" .Values.app.version "-" }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: greeting-sample-{{ regexReplaceAll "\\W+" .Values.app.version "-" }}
